name: build and deploy signal
on:
  push:
    branches:
      - master
      - main
jobs:
  Run-npm-on-Ubuntu:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: install ssh key
        shell: bash
        env:
          ID_RSA: ${{secrets.ID_RSA}}
          SSHCONFIG: ${{secrets.SSHCONFIG}}
          VERSION: "6.10.0"
        run: |
          mkdir -p ~/.ssh
          echo "$ID_RSA" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSHCONFIG" > ~/.ssh/config
      - name: checkout code
        uses: actions/checkout@v3
      - name: install deps
        shell: bash
        run: |
          sudo apt update
          sudo apt install -qq bash rsync podman flatpak elfutils coreutils slirp4netns rootlesskit binfmt-support fuse-overlayfs flatpak-builder qemu-user-static
      - name: build deb
        shell: bash
        run: |
          set -x
          bash ci-build.sh
          podman stop signal-desktop-$VERSION
          cp ~/signal-desktop.deb .
      - name: install flatpak deps
        shell: bash
        run: |
          sudo mkdir -p /opt/pakrepo
          sudo chown build /opt/pakrepo
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install --noninteractive --arch=aarch64 flathub org.electronjs.Electron2.BaseApp//22.08 org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08 -y
      - name: build flatpak
        shell: bash
        run: |
          flatpak-builder --arch=aarch64 --gpg-sign=FBEF43DC8C6BE9A7 --repo=/opt/pakrepo --force-clean .builddir flatpak.yml
      - name: sync to server
        shell: bash
        run: |
          rsync -azu --delete /opt/pakrepo/ server:/var/www/htdocs/elagost.com/flatpak/repo_signal_ci/
